<?php

return [
  '0100-0000-10' => [
    'price' => 1.02,
    'category' => 'Кисти малярные',
    'model' => 'Кисть плоская СТАНДАРТ, натуральный ворс',
    'variant' => '1/25мм',
    'unit' => 'шт.',
    'upakMal' => 12,
    'upakKrup' => 1200,
    'uri' => '/catalog/kisti-malyarnyie/kist-plosk-stndrt-nat-vors-',
    'img' => '',
    'galleryImgs' => [],
  ],
  '0100-0000-15' => [
    'price' => 1.25,
    'category' => 'Кисти малярные',
    'model' => 'Кисть плоская СТАНДАРТ, натуральный ворс',
    'variant' => '1,5/38мм',
    'unit' => 'шт.',
    'upakMal' => 12,
    'upakKrup' => 1200,
    'uri' => '/catalog/kisti-malyarnyie/kist-plosk-stndrt-nat-vors-1,5-38',
    'img' => '',
    'galleryImgs' => [],
  ],
  '0100-0000-20' => [
    'price' => 1.60,
    'category' => 'Кисти малярные',
    'model' => 'Кисть плоская СТАНДАРТ, натуральный ворс',
    'variant' => '2/50мм',
    'unit' => 'шт.',
    'upakMal' => 12,
    'upakKrup' => 600,
    'uri' => '/catalog/kisti-malyarnyie/kist-plosk-stndrt-nat-vors-2-50',
    'img' => '',
    'galleryImgs' => [],
  ],
  '0100-0000-25' => [
    'price' => 2.05,
    'category' => 'Кисти малярные',
    'model' => 'Кисть плоская СТАНДАРТ, натуральный ворс',
    'variant' => '2,5/63мм',
    'unit' => 'шт.',
    'upakMal' => 12,
    'upakKrup' => 480,
    'uri' => '/catalog/kisti-malyarnyie/kist-plosk-stndrt-nat-vors-2,5-63',
    'img' => '',
    'galleryImgs' => [],
  ],
  '0100-0000-30' => [
    'price' => 2.05,
    'category' => 'Кисти малярные',
    'model' => 'Кисть плоская СТАНДАРТ, натуральный ворс',
    'variant' => '3/75мм',
    'unit' => 'шт.',
    'upakMal' => 12,
    'upakKrup' => 480,
    'uri' => '/catalog/kisti-malyarnyie/kist-plosk-stndrt-nat-vors-2-50',
    'img' => '',
    'galleryImgs' => [],
  ],
  '0100-0000-40' => [
    'price' => 2.05,
    'category' => 'Кисти малярные',
    'model' => 'Кисть плоская СТАНДАРТ, натуральный ворс',
    'variant' => '4/100мм',
    'unit' => 'шт.',
    'upakMal' => 12,
    'upakKrup' => 480,
    'uri' => '/catalog/kisti-malyarnyie/kist-plosk-stndrt-nat-vors-4-100',
    'img' => '',
    'galleryImgs' => [],
  ],
];