<?php

return [
    '0100-0000-10' => [
    'price' => 1.02,
    'category' => 'Кисти малярные',
    'model' => 'Кисть плоская СТАНДАРТ, натуральный ворс',
    'variant' => '1/25мм',
    'unit' => 'шт',
    'upakMal' => 12,
    'upakKrup' => 1200,
    'uri' => '/catalog/kisti-malyarnyie/kist-plosk-stndrt-nat-vors-1-25',
    'img' => '',
    'galleryImgs' => [],
],
  '0100-0000-15' => [
    'price' => 1.25,
    'category' => 'Кисти малярные',
    'model' => 'Кисть плоская СТАНДАРТ, натуральный ворс',
    'variant' => '1,5/38мм',
    'unit' => 'шт',
    'upakMal' => 12,
    'upakKrup' => 1200,
    'uri' => '/catalog/kisti-malyarnyie/kist-plosk-stndrt-nat-vors-1,5-38',
    'img' => '',
    'galleryImgs' => [],
],
  '0100-0000-20' => [
    'price' => 1.60,
    'category' => 'Кисти малярные',
    'model' => 'Кисть плоская СТАНДАРТ, натуральный ворс',
    'variant' => '2/50мм',
    'unit' => 'шт',
    'upakMal' => 12,
    'upakKrup' => 600,
    'uri' => '/catalog/kisti-malyarnyie/kist-plosk-stndrt-nat-vors-2-50',
    'img' => '',
    'galleryImgs' => [],
],
  '0100-0000-25' => [
    'price' => 2.05,
    'category' => 'Кисти малярные',
    'model' => 'Кисть плоская СТАНДАРТ, натуральный ворс',
    'variant' => '2,5/63мм',
    'unit' => 'шт',
    'upakMal' => 12,
    'upakKrup' => 480,
    'uri' => '/catalog/kisti-malyarnyie/kist-plosk-stndrt-nat-vors-2,5-63',
    'img' => '',
    'galleryImgs' => [],
],
  '0100-0000-30' => [
    'price' => 2.88,
    'category' => 'Кисти малярные',
    'model' => 'Кисть плоская СТАНДАРТ, натуральный ворс',
    'variant' => '3/75мм',
    'unit' => 'шт',
    'upakMal' => 12,
    'upakKrup' => 360,
    'uri' => '/catalog/kisti-malyarnyie/kist-plosk-stndrt-nat-vors-3-75',
    'img' => '',
    'galleryImgs' => [],
],
  '0100-0000-40' => [
    'price' => 4.00,
    'category' => 'Кисти малярные',
    'model' => 'Кисть плоская СТАНДАРТ, натуральный ворс',
    'variant' => '4/100мм',
    'unit' => 'шт',
    'upakMal' => 12,
    'upakKrup' => 240,
    'uri' => '/catalog/kisti-malyarnyie/kist-plosk-stndrt-nat-vors-4-100',
    'img' => '',
    'galleryImgs' => [],
],
  '0100-0000-50' => [
    'price' => 4.99,
    'category' => 'Кисти малярные',
    'model' => 'Кисть плоская СТАНДАРТ, натуральный ворс',
    'variant' => '5/125мм',
    'unit' => 'шт',
    'upakMal' => 12,
    'upakKrup' => 240,
    'uri' => '/catalog/kisti-malyarnyie/kist-plosk-stndrt-nat-vors-5-125',
    'img' => '',
    'galleryImgs' => [],
],
  '0110-0000-10' => [
    'price' => 1.54,
    'category' => 'Кисти малярные',
    'model' => 'Кисть плоская ЕВРО, натуральный ворс',
    'variant' => '1/25мм',
    'unit' => 'шт',
    'upakMal' => 12,
    'upakKrup' => 600,
    'uri' => '/catalog/kisti-malyarnyie/kist-plosk-evro-nat-vors-1-25',
    'img' => '',
    'galleryImgs' => [],
],
  '0110-0000-15' => [
    'price' => 2.08,
    'category' => 'Кисти малярные',
    'model' => 'Кисть плоская ЕВРО, натуральный ворс',
    'variant' => '1,5/38мм',
    'unit' => 'шт',
    'upakMal' => 12,
    'upakKrup' => 600,
    'uri' => '/catalog/kisti-malyarnyie/kist-plosk-evro-nat-vors-1,5-38',
    'img' => '',
    'galleryImgs' => [],
],
  '0110-0000-20' => [
    'price' => 3.11,
    'category' => 'Кисти малярные',
    'model' => 'Кисть плоская ЕВРО, натуральный ворс',
    'variant' => '2/50мм',
    'unit' => 'шт',
    'upakMal' => 12,
    'upakKrup' => 300,
    'uri' => '/catalog/kisti-malyarnyie/kist-plosk-evro-nat-vors-2-50',
    'img' => '',
    'galleryImgs' => [],
],
  '0110-0000-25' => [
    'price' => 4.16,
    'category' => 'Кисти малярные',
    'model' => 'Кисть плоская ЕВРО, натуральный ворс',
    'variant' => '2,5/63мм',
    'unit' => 'шт',
    'upakMal' => 12,
    'upakKrup' => 300,
    'uri' => '/catalog/kisti-malyarnyie/kist-plosk-evro-nat-vors-2,5-63',
    'img' => '',
    'galleryImgs' => [],
],
  '0110-0000-30' => [
    'price' => 5.86,
    'category' => 'Кисти малярные',
    'model' => 'Кисть плоская ЕВРО, натуральный ворс',
    'variant' => '3/75мм',
    'unit' => 'шт',
    'upakMal' => 12,
    'upakKrup' => 240,
    'uri' => '/catalog/kisti-malyarnyie/kist-plosk-evro-nat-vors-3-75',
    'img' => '',
    'galleryImgs' => [],
],
  '0110-0000-40' => [
    'price' => 6.72,
    'category' => 'Кисти малярные',
    'model' => 'Кисть плоская ЕВРО, натуральный ворс',
    'variant' => '4/100мм',
    'unit' => 'шт',
    'upakMal' => 12,
    'upakKrup' => 120,
    'uri' => '/catalog/kisti-malyarnyie/kist-plosk-evro-nat-vors-4-100',
    'img' => '',
    'galleryImgs' => [],
],
  '0230-0030-07' => [
    'price' => 3.94,
    'category' => 'Кисти малярные',
    'model' => 'Кисть лавковец мини, натуральный ворс',
    'variant' => '70х30мм',
    'unit' => 'шт',
    'upakMal' => 12,
    'upakKrup' => 300,
    'uri' => '/catalog/kisti-malyarnyie/kist-lavkovets-mini-nat-vors-70-30',
    'img' => '',
    'galleryImgs' => [],
],
  '0230-0030-10' => [
    'price' => 5.95,
    'category' => 'Кисти малярные',
    'model' => 'Кисть лавковец мини, натуральный ворс',
    'variant' => '100х30мм',
    'unit' => 'шт',
    'upakMal' => 12,
    'upakKrup' => 180,
    'uri' => '/catalog/kisti-malyarnyie/kist-lavkovets-mini-nat-vors-100-30',
    'img' => '',
    'galleryImgs' => [],
],
  '0230-0030-12' => [
    'price' => 7.26,
    'category' => 'Кисти малярные',
    'model' => 'Кисть лавковец мини, натуральный ворс',
    'variant' => '120х30мм',
    'unit' => 'шт',
    'upakMal' => 12,
    'upakKrup' => 180,
    'uri' => '/catalog/kisti-malyarnyie/kist-lavkovets-mini-nat-vors-120-30',
    'img' => '',
    'galleryImgs' => [],
],
  '0230-0040-14' => [
    'price' => 8.99,
    'category' => 'Кисти малярные',
    'model' => 'Кисть лавковец мини, натуральный ворс',
    'variant' => '140х40мм',
    'unit' => 'шт',
    'upakMal' => 6,
    'upakKrup' => 120,
    'uri' => '/catalog/kisti-malyarnyie/kist-lavkovets-mini-nat-vors-140-40',
    'img' => '',
    'galleryImgs' => [],
],
  '0230-0050-15' => [
    'price' => 10.85,
    'category' => 'Кисти малярные',
    'model' => 'Кисть лавковец мини, натуральный ворс',
    'variant' => '150х50мм',
    'unit' => 'шт',
    'upakMal' => 6,
    'upakKrup' => 120,
    'uri' => '/catalog/kisti-malyarnyie/kist-lavkovets-mini-nat-vors-150-50',
    'img' => '',
    'galleryImgs' => [],
],

];