<?php

return [
    '0100-0000-10' => [
    'price' => 1.02,
    'category' => 'Кисти малярные',
    'model' => 'Кисть плоская СТАНДАРТ, натуральный ворс',
    'variant' => '1/25мм',
    'unit' => 'шт',
    'upakMal' => 12,
    'upakKrup' => 1200,
    'uri' => '/catalog/kisti-malyarnyie/kist-plosk-stndrt-nat-vors-1-25',
    'img' => '',
    'galleryImgs' => [
      'some/path/to/img-1',
      'some/path/to/img-2',
    ],
],
  '0100-0000-15' => [
    'price' => 1.25,
    'category' => 'Кисти малярные',
    'model' => 'Кисть плоская СТАНДАРТ, натуральный ворс',
    'variant' => '1,5/38мм',
    'unit' => 'шт',
    'upakMal' => 12,
    'upakKrup' => 1200,
    'uri' => '/catalog/kisti-malyarnyie/kist-plosk-stndrt-nat-vors-1,5-38',
    'img' => '',
    'galleryImgs' => [
      'some/path/to/img-1',
      'some/path/to/img-2',
    ],
],
  '0100-0000-20' => [
    'price' => 1.60,
    'category' => 'Кисти малярные',
    'model' => 'Кисть плоская СТАНДАРТ, натуральный ворс',
    'variant' => '2/50мм',
    'unit' => 'шт',
    'upakMal' => 12,
    'upakKrup' => 600,
    'uri' => '/catalog/kisti-malyarnyie/kist-plosk-stndrt-nat-vors-2-50',
    'img' => '',
    'galleryImgs' => [
      'some/path/to/img-1',
      'some/path/to/img-2',
    ],
],
  '0100-0000-25' => [
    'price' => 2.05,
    'category' => 'Кисти малярные',
    'model' => 'Кисть плоская СТАНДАРТ, натуральный ворс',
    'variant' => '2,5/63мм',
    'unit' => 'шт',
    'upakMal' => 12,
    'upakKrup' => 480,
    'uri' => '/catalog/kisti-malyarnyie/kist-plosk-stndrt-nat-vors-2,5-63',
    'img' => '',
    'galleryImgs' => [
      'some/path/to/img-1',
      'some/path/to/img-2',
    ],
],
  '0100-0000-30' => [
    'price' => 2.88,
    'category' => 'Кисти малярные',
    'model' => 'Кисть плоская СТАНДАРТ, натуральный ворс',
    'variant' => '3/75мм',
    'unit' => 'шт',
    'upakMal' => 12,
    'upakKrup' => 360,
    'uri' => '/catalog/kisti-malyarnyie/kist-plosk-stndrt-nat-vors-3-75',
    'img' => '',
    'galleryImgs' => [
      'some/path/to/img-1',
      'some/path/to/img-2',
    ],
],
  '0100-0000-40' => [
    'price' => 4.00,
    'category' => 'Кисти малярные',
    'model' => 'Кисть плоская СТАНДАРТ, натуральный ворс',
    'variant' => '4/100мм',
    'unit' => 'шт',
    'upakMal' => 12,
    'upakKrup' => 240,
    'uri' => '/catalog/kisti-malyarnyie/kist-plosk-stndrt-nat-vors-4-100',
    'img' => '',
    'galleryImgs' => [
      'some/path/to/img-1',
      'some/path/to/img-2',
    ],
],
  '0100-0000-50' => [
    'price' => 4.99,
    'category' => 'Кисти малярные',
    'model' => 'Кисть плоская СТАНДАРТ, натуральный ворс',
    'variant' => '5/125мм',
    'unit' => 'шт',
    'upakMal' => 12,
    'upakKrup' => 240,
    'uri' => '/catalog/kisti-malyarnyie/kist-plosk-stndrt-nat-vors-5-125',
    'img' => '',
    'galleryImgs' => [
      'some/path/to/img-1',
      'some/path/to/img-2',
    ],
],

];